version: '3.9'

services:
    mysql_db:
        image: mysql:5.5
        container_name: mysql_container
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_USER: user
          MYSQL_PASSWORD: password

    redis_db:
        image: redis
        container_name: redis_container
        ports:
          - '6379:6379'

    app:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: spring_container
        depends_on:
          - mysql_db
          - redis_db
        ports:
          - '8080:8080'
        environment:
          SPRING_PROFILES_ACTIVE: local
          MYSQL_DB_HOST: mysql_db
          MYSQL_DB_NAME: test
          MYSQL_DB_USER: user
          MYSQL_DB_PASS: password
          REDIS_DB_HOST: redis_db
          REDIS_DB_PORT: 6379
          REDIS_DB_PASS: root

